### ISSUE TITLE
Ctrl+Backspace in terminal window removes one character at a time instead of whole words

### ISSUE THREAD

**Issue by clboles** [dgriffen/WhackWhackTerminal#11]

**Comment by dgriffen** [comment]
Scheduling this for after I achieve parity with VSCode features since the terminal in VSCode currently does not implement this.

**Comment by Tyriar** [comment]
This may not be possible reliably on Windows, some more details here: https://github.com/Microsoft/vscode/issues/30276

**Comment by dgriffen** [comment]
This issue was moved to Microsoft/WhackWhackTerminal#13
