### ISSUE TITLE
Ctrl+\,Ctrl+\ activates the terminal window but does not focus the terminal for input

### ISSUE THREAD

**Issue by clboles** [dgriffen/WhackWhackTerminal#12]
When using Ctrl+\ ,Ctrl+\ to jump back to the terminal window from elsewhere in VS, the user should be able to immediately start typing in the terminal.  As currently implemented, they have to tab once to reach the terminal before being able to type.

**Comment by garethj-msft** [comment]
I think that's really more of a bug.

**Comment by dgriffen** [comment]
This issue was moved to Microsoft/WhackWhackTerminal#14
