### ISSUE TITLE
CTRL-C on a line when something isn't selected should send a break

### ISSUE THREAD

**Issue by shanselman** [dgriffen/WhackWhackTerminal#15]
CTRL-C on a line when something isn't selected should send a break (that is, cancel the command and go to a clear line) instead of outputting ^c.

**Comment by dgriffen** [comment]
It should currently be doing that. Can you give some more context into what you mean?

**Comment by shanselman** [comment]
Go into cmd.exe, type test, then ctrl-c. The command is cancelled and you get a new prompt. In WhackWhack you either get a "^C" output OR nothing happens.

**Comment by dgriffen** [comment]
test isn't recognized as a command for me. Is it a program you installed?

**Comment by Tyriar** [comment]
Here's the upstream issue https://github.com/Tyriar/node-pty/issues/7 for this. This is one of the problems that is very difficult because of the nature of the backing library [winpty](https://github.com/rprichard/winpty).

You can however press esc to reliably clear the line in cmd and powershell.

**Comment by shanselman** [comment]
Thanks @Tyriar.

@dgriffen It's not a exe, it's just text...try it in cmd.exe. Type some stuff and hit ctrl+C. It's different behavior from ESC as @Tyriar suggests.

**Comment by dgriffen** [comment]
This issue was moved to Microsoft/WhackWhackTerminal#16
