### ISSUE TITLE
Can we port the open issues to the Microsoft repo please?

### ISSUE THREAD

**Issue by garethj-msft** [dgriffen/WhackWhackTerminal#19]
Would you like us to go and open equivalent ones, so the users are right?

**Comment by dgriffen** [comment]
I looked into porting the existing issues and there doesn't appear to be a good built in way to do that. If you know of one that would be great.

**Comment by garethj-msft** [comment]
https://github-issue-mover.appspot.com/

**Comment by dgriffen** [comment]
This issue was moved to Microsoft/WhackWhackTerminal#19
