### ISSUE TITLE
always have to import module

### ISSUE THREAD

**Issue by dasjestyr** [dgriffen/WhackWhackTerminal#20]
Is it normal to have to run Import-Module posh-git every time visual is restarted? It seems every time I restart, all the modules are reset

**Comment by dgriffen** [comment]
The reason is that posh-git hasn't been added to the profile that is used by the terminal. You can add it permanently with the command `Add-PoshGitToProfile`

**Comment by dgriffen** [comment]
Also, I should point out that the repository has moved [here](https://github.com/Microsoft/WhackWhackTerminal)

**Comment by dasjestyr** [comment]
oh nice thanks!
